FROM node:22-alpine AS build

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./

COPY apps/frontend/package.json ./apps/frontend/
COPY packages/ui/package.json ./packages/ui/
COPY packages/schemas/package.json ./packages/schemas/
COPY packages/eslint-config/package.json ./packages/eslint-config/
COPY packages/typescript-config/package.json ./packages/typescript-config/

RUN pnpm i --frozen-lockfile

COPY apps/frontend/ ./apps/frontend/
COPY packages/ui/ ./packages/ui/
COPY packages/schemas/ ./packages/schemas/
COPY packages/eslint-config/ ./packages/eslint-config/
COPY packages/typescript-config/ ./packages/typescript-config/

ARG VITE_API_URL=/api
ARG VITE_API_TIMEOUT=10000
ENV VITE_API_URL=$VITE_API_URL VITE_API_TIMEOUT=$VITE_API_TIMEOUT

RUN pnpm -F frontend build

FROM nginx:alpine AS runtime

COPY --from=build /app/apps/frontend/dist /usr/share/nginx/html
COPY apps/frontend/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
