FROM node:22-alpine AS build

RUN corepack enable

WORKDIR /app

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./

COPY apps/backend/package.json ./apps/backend/
COPY packages/database/package.json ./packages/database/
COPY packages/schemas/package.json ./packages/schemas/
COPY packages/eslint-config/package.json ./packages/eslint-config/
COPY packages/typescript-config/package.json ./packages/typescript-config/

RUN pnpm i --frozen-lockfile

COPY apps/backend/ ./apps/backend/
COPY packages/database/ ./packages/database/
COPY packages/schemas/ ./packages/schemas/
COPY packages/eslint-config/ ./packages/eslint-config/
COPY packages/typescript-config/ ./packages/typescript-config/

RUN pnpm -F backend build
RUN pnpm -F backend deploy --prod /prod/backend

FROM node:22-alpine AS runtime

WORKDIR /app

ENV NODE_ENV=production

COPY --from=build /prod/backend .

RUN addgroup -S app && adduser -S app -G app
USER app

EXPOSE 3000

CMD [ "node", "dist/serve.js" ]
